genCode:
  upstream:
    http:
      common:
        hostName: localhost
        port: 8080
app:
  fstype: "mem"
  # fstype: os for os filesystem,  memory for in-memory fs or gcs for gcs bucket
  cachelocation: "gop1234"
  # cachelocation is the cache directory or gcs bucket name
